# Generated by Django 5.0 on 2024-01-29 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bolim', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fan_nomi', models.CharField(max_length=200)),
                ('Rasm', models.ImageField(upload_to='img')),
                ('Ustoz', models.CharField(max_length=500)),
                ('Ustoz_rasmi', models.ImageField(upload_to='ustoz')),
                ('Malumot', models.TextField()),
                ('Bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bolimlar')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
        ),
        migrations.CreateModel(
            name='Vazifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.TextField()),
                ('video', models.FileField(upload_to='video')),
                ('Fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fan')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='nomi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vazifa'),
        ),
    ]
